name: "Deploy Cloud Function"

inputs:
  name:
    required: true
    type: "string"
  project-id:
    required: true
    type: "string"
  infra-manager-service-account:
    required: true
    type: "string"
  region:
    required: true
    type: "string"

runs:
  using: "composite"
  steps:
    - name: "Apply Terraform"
      run: |
        gcloud infra-manager deployments apply \
          "projects/${{ inputs.project-id }}/locations/${{ inputs.region }}/deployments/${{ inputs.name }}" \
          --local-source="./modules/${{ inputs.name }}" \
          --service-account="projects/${{ inputs.project-id }}/serviceAccounts/${{ inputs.infra-manager-service-account }}" \
          --input-values="project_id=${{ inputs.project-id }}"
