project_id                    = "www-kaito-tokyo-1-svc-my1a"
cloudbuild_trigger_repository = "projects/www-kaito-tokyo-1-svc-my1a/locations/asia-east1/connections/kaito-tokyo/repositories/kaito-tokyo-www.kaito.tokyo"
tmp_dir                       = "/tmp"
cdn_region                    = "auto"
cdn_endpoint                  = "https://1169b990c0885e4cfa603c38eef1a9b3.r2.cloudflarestorage.com"
cdn_bucket_name               = "www-img-kaito-tokyo"
