name: "setup-buildkit"

runs:
  using: "composite"

  steps:
    - name: "Download and install buildkit"
      shell: "bash"
      env:
        GH_TOKEN: "${{ github.token }}"
      working-directory: "/tmp"
      run: |
        gh release download ${{ inputs.version }} -R "moby/buildkit" --pattern "buildkit-*.linux-amd64.tar.gz"
        sudo tar -xzf buildkit-*.linux-amd64.tar.gz -C /usr/local

    - name: "Start buildkitd"
      shell: "bash"
      run: "sudo buildkitd --group=docker &"
