name: "setup-buildkit"

defaults:
  run:
    shell: "bash"

runs:
  using: "composite"
  
  steps:
    - name: "Download and install buildkit"
      run: |
        gh release download ${{ inputs.version }} -R "moby/buildkit" --pattern "buildkit-*.linux-amd64.tar.gz"
        tar -xzf buildkit-*.linux-amd64.tar.gz -C /usr/local
    
    - name: "Start buildkitd"
      run: "buildkitd &"
