name: "Deploy Cloud Function"

inputs:
  name:
    required: true
    type: "string"
  working-directory:
    required: true
    type: "string"
  region:
    required: true
    type: "string"
  function-service-account:
    required: true
    type: "string"

runs:
  using: "composite"
  steps:
    - name: "Deploy Function"
      working-directory: "${{ inputs.working-directory }}"
      run: |
        gcloud functions deploy "${{ inputs.name }}" \
          --region="${{ inputs.region }}" \
          --no-allow-unauthenticated \
          --gen2 \
          --ingress-settings=internal-only \
          --run-service-account="${{ inputs.function-service-account }}" \
          --runtime=nodejs20 \
          --service-account="${{ inputs.function-service-account }}" \
          --trigger-http
