options:
  logging: "CLOUD_LOGGING_ONLY"
steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "gcloud"
      - "functions"
      - "deploy"
      - "newt-storage-optimize-image"
      - "--region=asia-east1"
      - "--no-allow-unauthenticated"
      - "--gen2"
      - "--ingress-settings=internal-only"
      - "--run-service-account=${_RUN_SERVICE_ACCOUNT}"
      - "--runtime=nodejs20"
      - "--service-account=${_SERVICE_ACCOUNT}"
      - "--trigger-http"
