options:
  logging: "CLOUD_LOGGING_ONLY"
steps:
  - name: "hashicorp/terraform:1.7.3"
    dir: "organization-terraform"
    args:
      - "init"
      - "-no-color"
  - name: "hashicorp/terraform:1.7.3"
    dir: "organization-terraform"
    args:
      - "plan"
      - "-no-color"
  - name: "hashicorp/terraform:1.7.3"
    dir: "organization-terraform"
    args:
      - "apply"
      - "-no-color"
      - "-auto-approve"
