options:
  logging: "CLOUD_LOGGING_ONLY"
steps:
  - name: "hashicorp/terraform:1.7.3"
    dir: "terraform/environments/prod1"
    args:
      - "init"
      - "-no-color"

  - name: "hashicorp/terraform:1.7.3"
    dir: "terraform/environments/prod1"
    args:
      - "plan"
      - "-no-color"
      - "-target=module.newt_storage.google_artifact_registry_repository.run"
      - "-out=ar.tfplan"

  - name: "hashicorp/terraform:1.7.3"
    dir: "terraform/environments/prod1"
    args:
      - "apply"
      - "-no-color"
      - "-auto-approve"
      - "ar.tfplan"

  - name: "hashicorp/terraform:1.7.3"
    dir: "terraform/environments/prod1"
    entrypoint: "bash"
    args:
      - "-c"
      - "terraform output module.newt_storage.run_repository > run_repository"

  - name: "gcr.io/k8s-skaffold/pack"
    entrypoint: "bash"
    args:
      - "-c"
      - "pack build $(<run_repository)/newt-storage --path=packages/newt-storage --builder=gcr.io/buildpacks/builder:latest"

  - name: "hashicorp/terraform:1.7.3"
    dir: "terraform/environments/prod1"
    args:
      - "plan"
      - "-no-color"
      - "-out=tfplan"

  - name: "hashicorp/terraform:1.7.3"
    dir: "terraform/environments/prod1"
    args:
      - "apply"
      - "-no-color"
      - "-auto-approve"
      - "tfplan"
