name: "apply-terraform-main"

on:
  workflow_call:
    inputs:
      run-image:
        required: true
        type: "string"

jobs:
  ApplyTerraformMain:
    runs-on: "ubuntu-24.04"

    timeout-minutes: 30

    permissions:
      contents: "read"
      id-token: "write"

    defaults:
      run:
        working-directory: "terraform/environments/prod1"

    steps:
      - name: "Setup Terraform"
        uses: "hashicorp/setup-terraform@v3"

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        id: "google-github-actions-auth"
        with:
          workload_identity_provider: "projects/643615470006/locations/global/workloadIdentityPools/github-kaito-tokyo/providers/actions-githubusercontent-com"
          service_account: "yf-push-gha-main@www-kaito-tokyo-1-svc-my1a.iam.gserviceaccount.com"

      - name: "Init Terraform"
        run: "terraform init"

      - name: "Plan Terraform"
        run: "terraform plan -input=false -out=tfplan -var=run_image=${{ inputs.run-image }}"

      - name: "Apply Terraform"
        run: "terraform apply -auto-approve tfplan"
