name: "Deploy Cloud Function"
run-name: "${{ inputs.name }}"

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: "string"
      infra-manager-service-account:
        required: true
        type: "string"
      region:
        required: true
        type: "string"
    secrets:
      project-id:
        required: true
      project-number:
        required: true
      wif-pool-id:
        required: true
      wif-provider-id:
        required: true
      wif-service-account:
        required: true

jobs:
  DeployInfraManager:
    name: "Deploy Infra Manager ${ inputs.name }"

    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Google Cloud"
        uses: "./.github/actions/setup-google-cloud"
        with:
          project-number: "${{ secrets.project-number }}"
          pool-id: "${{ secrets.wif-pool-id }}"
          provider-id: "${{ secrets.wif-provider-id }}"
          service-account: "${{ secrets.wif-service-account }}"

      - name: "Apply Terraform"
        run: |
          gcloud infra-manager deployments apply \
            "projects/${{ secrets.project-id }}/locations/${{ inputs.region }}/deployments/${{ inputs.name }}" \
            --local-source="./modules/${{ inputs.name }}" \
            --service-account="projects/${{ secrets.project-id }}/serviceAccounts/${{ inputs.infra-manager-service-account }}" \
            --input-values="project_id=${{ secrets.project-id }}"
