name: "image-publish-main"

on:
  workflow_call:

jobs:
  ImagePublishMain:
    runs-on: "ubuntu-24.04"

    steps:
      - name: "Setup buildkit"
        uses: "./.github/actions/setup-buildkit"

      - name: "Checkout"
        uses: "actions/checkout@v4"

