name: "Prettier"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  CheckPrettier:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install npm depndencies"
        run: "npm ci"

      - name: "Check prettier"
        run: "npm exec -- prettier --check ."
