name: "push-main"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  PushMain:
    runs-on: "ubuntu-22.04"

    steps:
      - uses: "./.github/workflows/image-publish-main.yaml"
