name: "push-main"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  # ImagePublishMain:
  #   uses: "./.github/workflows/image-publish-main.yaml"
  #   permissions:
  #     contents: "read"
  #     id-token: "write"

  ApplyTerraformMain:
    uses: "./.github/workflows/apply-terraform-main.yaml"
    permissions:
      contents: "read"
      id-token: "write"
    with:
      run-image: "busybox"
