name: "Terraform fmt"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  CheckTerraformFormat:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Install terraform"
        uses: "hashicorp/setup-terraform@v3"

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Check format"
        run: "terraform fmt -check -recursive terraform/environments terraform/modules"
