name: "terraform-plan-pr"

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  TerraformPlan:
    runs-on: "ubuntu-latest"

    timeout-minutes: 10

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Install terraform"
        uses: "hashicorp/setup-terraform@v3"

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: "projects/643615470006/locations/global/workloadIdentityPools/github-kaito-tokyo/providers/actions-githubusercontent-com"
          service_account: "wkt-terraform-gha-pr@www-kaito-tokyo-1-svc-my1a.iam.gserviceaccount.com"

      - name: "Terraform Init"
        working-directory: "terraform/environments/prod1"
        run: "terraform init"

      - name: "Terraform Plan"
        working-directory: "terraform/environments/prod1"
        run: |
          terraform plan \
          -input=false \
          -lock=false \
          -var=newt_storage_run_image=invalid \
          -var=youtube_fetcher_run_image=invalid \
