name: "terraform-fmt"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref != 'refs/heads/main' }}"

jobs:
  erraformFmt:
    runs-on: "ubuntu-latest"

    timeout-minutes: 10

    steps:
      - name: "Install terraform"
        uses: "hashicorp/setup-terraform@v3"

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Check format"
        run: "terraform fmt -check -recursive terraform/environments terraform/modules"
