name: "upload-images"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: "bash"

jobs:
  UploadImages:
    runs-on: "ubuntu-24.04"

    steps:
      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends rclone

      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Copy images"
        env:
          RCLONE_CONFIG_R2_TYPE: "s3"
          RCLONE_CONFIG_R2_PROVIDER: "Cloudflare"
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: "${{ secrets.RCLONE_CONFIG_R2_ACCESS_KEY_ID }}"
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: "${{ secrets.RCLONE_CONFIG_R2_SECRET_ACCESS_KEY }}"
          RCLONE_CONFIG_R2_ENDPOINT: "${{ secrets.RCLONE_CONFIG_R2_ENDPOINT }}"
        run: |
          rclone copy packages/www/src/routes/artworks r2:www-img-kaito-tokyo/artworks \
            --include="*.{png,webp,jpg}" \
            --progress
