name: "YouTube Fetcher"

on:
  workflow_call:
    inputs:
      infra-manager-service-account:
        required: true
        type: "string"
      function-service-account:
        required: true
        type: "string"
      region:
        required: true
        type: "string"
    secrets:
      project-id:
        required: true
      project-number:
        required: true
      wif-pool-id:
        required: true
      wif-provider-id:
        required: true
      wif-service-account:
        required: true

jobs:
  DeployYouTubeFetcherInfra:
    uses: "./.github/workflows/deploy-infra-manager.yaml"
    with:
      name: "youtube-fetcher"
      infra-manager-service-account: "${{ inputs.infra-manager-service-account }}"
      region: "${{ inputs.region }}"
      input-values: "project_id=${{ inputs.project-id }}"
    secrets: "inherit"

  DeployYouTubeFetcherDigest:
    needs:
      - "DeployYouTubeFetcherInfra"
    uses: "./.github/workflows/deploy-cloud-function.yaml"
    with:
      name: "youtube-fetcher-digest"
      working-directory: "serverless/youtube-fetcher"
      region: "${{ inputs.region }}"
      function-service-account: "${{ inputs.function-service-account }}"
    secrets: "inherit"

  DeployYouTubeFetcherListSearch:
    needs:
      - "DeployYouTubeFetcherInfra"
    uses: "./.github/workflows/deploy-cloud-function.yaml"
    with:
      name: "youtube-fetcher-list-search"
      working-directory: "serverless/youtube-fetcher"
      region: "${{ inputs.region }}"
      function-service-account: "${{ inputs.function-service-account }}"
    secrets: "inherit"

  DeployYouTubeFetcherListVideos:
    needs:
      - "DeployYouTubeFetcherInfra"
    uses: "./.github/workflows/deploy-cloud-function.yaml"
    with:
      name: "youtube-fetcher-list-videos"
      working-directory: "serverless/youtube-fetcher"
      region: "${{ inputs.region }}"
      function-service-account: "${{ inputs.function-service-account }}"
    secrets: "inherit"
