name: "YouTube Fetcher"

on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - "opened"
      - "labeled"
      - "synchronize"
      - "auto_merge_enabled"
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  PROJECT_ID: "www-kaito-tokyo"
  PROJECT_NUMBER: "641342314523"
  POOL_ID: "github-umireon"
  PROVIDER_ID: "actions-githubusercontent-com"
  SERVICE_ACCOUNT: "gha-www-kaito-tokyo@www-kaito-tokyo.iam.gserviceaccount.com"
  INFRA_MANAGER_SERVICE_ACCOUNT: "infra-manager@www-kaito-tokyo.iam.gserviceaccount.com"
  FUNCTION_SERVICE_ACCOUNT: "youtube-fetcher@www-kaito-tokyo.iam.gserviceaccount.com"
  REGION: "asia-east1"

jobs:
  DeployYouTubeFetcher:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    if: "github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'infra')"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - uses: "./.github/actions/setup-google-cloud"

      - name: "Apply Terraform"
        run: |
          gcloud infra-manager deployments apply \
            "projects/$PROJECT_ID/locations/$REGION/deployments/youtube-fetcher" \
            --local-source="./modules/youtube-fetcher" \
            --service-account="projects/$PROJECT_ID/serviceAccounts/$INFRA_MANAGER_SERVICE_ACCOUNT" \
            --input-values="project_id=$PROJECT_ID"

      - name: "Deploy youtube-list-search"
        working-directory: "serverless/youtube-fetcher"
        run: |
          gcloud functions deploy youtube-list-search \
            --region=$REGION \
            --no-allow-unauthenticated \
            --gen2 \
            --ingress-settings=internal-only \
            --run-service-account=$FUNCTION_SERVICE_ACCOUNT \
            --runtime=nodejs20 \
            --service-account=$FUNCTION_SERVICE_ACCOUNT \
            --trigger-http

      - name: "Deploy youtube-list-videos"
        working-directory: "serverless/youtube-fetcher"
        run: |
          gcloud functions deploy youtube-list-videos \
            --region=$REGION \
            --no-allow-unauthenticated \
            --gen2 \
            --ingress-settings=internal-only \
            --run-service-account=$FUNCTION_SERVICE_ACCOUNT \
            --runtime=nodejs20 \
            --service-account=$FUNCTION_SERVICE_ACCOUNT \
            --trigger-http
