name: "YouTube Fetcher"

on:
  workflow_call:
    inputs:
      infra-manager-service-account:
        required: true
        type: "string"
      function-service-account:
        required: true
        type: "string"
      region:
        required: true
        type: "string"
    secrets:
      project-id:
        required: true
      project-number:
        required: true
      wif-pool-id:
        required: true
      wif-provider-id:
        required: true
      wif-service-account:
        required: true

jobs:
  DeployYouTubeFetcherInfra:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Google Cloud"
        uses: "./.github/actions/setup-google-cloud"
        with:
          project-number: "${{ secrets.project-number }}"
          pool-id: "${{ secrets.wif-pool-id }}"
          provider-id: "${{ secrets.wif-provider-id }}"
          service-account: "${{ secrets.wif-service-account }}"

      - name: "Deploy Infra Manager"
        uses: "./.github/actions/deploy-infra-manager"
        with:
          name: "youtube-fetcher"
          project-id: "${{ secrets.project-id }}"
          infra-manager-service-account: "${{ inputs.infra-manager-service-account }}"
          region: "${{ inputs.region }}"

  DeployYouTubeFetcherDigest:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    needs:
      - "DeployYouTubeFetcherInfra"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Google Cloud"
        uses: "./.github/actions/setup-google-cloud"
        with:
          project-number: "${{ secrets.project-number }}"
          pool-id: "${{ secrets.wif-pool-id }}"
          provider-id: "${{ secrets.wif-provider-id }}"
          service-account: "${{ secrets.wif-service-account }}"

      - name: "Deploy Function"
        uses: "./.github/actions/deploy-cloud-function"
        with:
          name: "youtube-fetcher-digest"
          working-directory: "serverless/youtube-fetcher"
          region: "${{ inputs.region }}"
          function-service-account: "${{ inputs.function-service-account }}"

  DeployYouTubeFetcherListSearch:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    needs:
      - "DeployYouTubeFetcherInfra"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Google Cloud"
        uses: "./.github/actions/setup-google-cloud"
        with:
          project-number: "${{ secrets.project-number }}"
          pool-id: "${{ secrets.wif-pool-id }}"
          provider-id: "${{ secrets.wif-provider-id }}"
          service-account: "${{ secrets.wif-service-account }}"

      - name: "Deploy Function"
        uses: "./.github/actions/deploy-cloud-function"
        with:
          name: "youtube-fetcher-list-search"
          working-directory: "serverless/youtube-fetcher"
          region: "${{ inputs.region }}"
          function-service-account: "${{ inputs.function-service-account }}"

  DeployYouTubeFetcherGenerateListVideosQueries:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    needs:
      - "DeployYouTubeFetcherInfra"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Google Cloud"
        uses: "./.github/actions/setup-google-cloud"
        with:
          project-number: "${{ secrets.project-number }}"
          pool-id: "${{ secrets.wif-pool-id }}"
          provider-id: "${{ secrets.wif-provider-id }}"
          service-account: "${{ secrets.wif-service-account }}"

      - name: "Deploy Function"
        uses: "./.github/actions/deploy-cloud-function"
        with:
          name: "youtube-fetcher-generate-list-videos-queries"
          working-directory: "serverless/youtube-fetcher"
          region: "${{ inputs.region }}"
          function-service-account: "${{ inputs.function-service-account }}"

  DeployYouTubeFetcherSaveListVideos:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    needs:
      - "DeployYouTubeFetcherInfra"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Google Cloud"
        uses: "./.github/actions/setup-google-cloud"
        with:
          project-number: "${{ secrets.project-number }}"
          pool-id: "${{ secrets.wif-pool-id }}"
          provider-id: "${{ secrets.wif-provider-id }}"
          service-account: "${{ secrets.wif-service-account }}"

      - name: "Deploy Function"
        uses: "./.github/actions/deploy-cloud-function"
        with:
          name: "youtube-fetcher-save-list-videos"
          working-directory: "serverless/youtube-fetcher"
          region: "${{ inputs.region }}"
          function-service-account: "${{ inputs.function-service-account }}"

  DeployYouTubeFetcherSplitListVideos:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    needs:
      - "DeployYouTubeFetcherInfra"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Setup Google Cloud"
        uses: "./.github/actions/setup-google-cloud"
        with:
          project-number: "${{ secrets.project-number }}"
          pool-id: "${{ secrets.wif-pool-id }}"
          provider-id: "${{ secrets.wif-provider-id }}"
          service-account: "${{ secrets.wif-service-account }}"

      - name: "Deploy Function"
        uses: "./.github/actions/deploy-cloud-function"
        with:
          name: "youtube-fetcher-split-list-videos"
          working-directory: "serverless/youtube-fetcher"
          region: "${{ inputs.region }}"
          function-service-account: "${{ inputs.function-service-account }}"
