name: "YouTube Fetcher"

on:
  push:
    branches:
      - "main"
  pull_request:
    types:
      - "opened"
      - "labeled"
      - "synchronize"
      - "auto_merge_enabled"
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  PROJECT_ID: "www-kaito-tokyo"
  PROJECT_NUMBER: "641342314523"
  POOL_ID: "github-umireon"
  PROVIDER_ID: "actions-githubusercontent-com"
  SERVICE_ACCOUNT: "gha-www-kaito-tokyo@www-kaito-tokyo.iam.gserviceaccount.com"
  INFRA_MANAGER_SERVICE_ACCOUNT: "infra-manager@www-kaito-tokyo.iam.gserviceaccount.com"
  FUNCTION_SERVICE_ACCOUNT: "youtube-fetcher@www-kaito-tokyo.iam.gserviceaccount.com"
  REGION: "asia-east1"

jobs:
  DeployYouTubeFetcherInfra:
    uses: "./.github/workflows/deploy-infra-manager.yaml"
    with:
      name: "youtube-fetcher"
      project-id: "${{ env.PROJECT_ID }}"
      infra-manager-service-account: "${{ env.INFRA_MANAGER_SERVICE_ACCOUNT }}"
      region: "${{ env.REGION }}"
      input-values: "project_id=${{ env.PROJECT_ID }}"

  DeployYouTubeFetcherDigest:
    needs:
      - "DeployYouTubeFetcherInfra"
    uses: "./.github/workflows/deploy-cloud-function.yaml"
    with:
      name: "youtube-fetcher-digest"
      working-directory: "serverless/youtube-fetcher"
      region: "${{ env.REGION }}"
      function-service-account: "${{ env.FUNCTION_SERVICE_ACCOUNT }}"
    secrets:
      project-number: "${{ env.PROJECT_NUMBER }}"
      pool-id: "${{ env.POOL_ID }}"
      provider-id: "${{ env.PROVIDER_ID }}"
      service-account: "${{ env.SERVICE_ACCOUNT }}"

  DeployYouTubeFetcherListSearch:
    needs:
      - "DeployYouTubeFetcherInfra"
    uses: "./.github/workflows/deploy-cloud-function.yaml"
    with:
      name: "youtube-fetcher-list-search"
      working-directory: "serverless/youtube-fetcher"
      region: "${{ env.REGION }}"
      function-service-account: "${{ env.FUNCTION_SERVICE_ACCOUNT }}"
    secrets:
      project-number: "${{ env.PROJECT_NUMBER }}"
      pool-id: "${{ env.POOL_ID }}"
      provider-id: "${{ env.PROVIDER_ID }}"
      service-account: "${{ env.SERVICE_ACCOUNT }}"

  DeployYouTubeFetcherListVideos:
    needs:
      - "DeployYouTubeFetcherInfra"
    uses: "./.github/workflows/deploy-cloud-function.yaml"
    with:
      name: "youtube-fetcher-list-videos"
      working-directory: "serverless/youtube-fetcher"
      region: "${{ env.REGION }}"
      function-service-account: "${{ env.FUNCTION_SERVICE_ACCOUNT }}"
    secrets:
      project-number: "${{ env.PROJECT_NUMBER }}"
      pool-id: "${{ env.POOL_ID }}"
      provider-id: "${{ env.PROVIDER_ID }}"
      service-account: "${{ env.SERVICE_ACCOUNT }}"
